# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa91f087db05639562fb8e69986de4c18f754dd6eda603c70b6fb6eb3e42edfb977adec1ed5f233facde5da9894b89e2f57269d00e1a7212137f349bf9ad967

test:
  secret_key_base: bb062b79916b0f17d9cc1ea7159f90f0b87a7276de397e6b0cf9c989b637c55415c3c5ac03a1a0fb6cd0b072bcb7bd9ea09778dd1f50730234ffc6b6ffb911e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
